# Generated by Django 2.1.3 on 2018-12-11 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyList',
            fields=[
                ('id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieseries.Movie')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
