# Generated by Django 2.2.1 on 2019-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0004_auto_20190527_1735'),
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='show',
        ),
        migrations.AddField(
            model_name='mylist',
            name='show',
            field=models.ManyToManyField(blank=True, to='movieseries.Movie', verbose_name='Shows'),
        ),
    ]
