# Generated by Django 2.2.1 on 2019-05-27 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0004_auto_20190527_1735'),
        ('mylist', '0002_auto_20190527_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist',
            name='show',
        ),
        migrations.AddField(
            model_name='mylist',
            name='show',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movieseries.Movie'),
        ),
    ]
