# Generated by Django 2.1.3 on 2018-12-11 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=200, verbose_name='Title')),
                ('title_translated', models.TextField(blank=True, max_length=200, verbose_name='Translated Title')),
                ('director', models.TextField(blank=True, max_length=150, verbose_name='Director')),
                ('description', models.TextField(blank=True, max_length=200, verbose_name='Description')),
                ('added', models.DateField(auto_now_add=True, verbose_name='Added')),
                ('movie_year', models.PositiveSmallIntegerField(blank=True, verbose_name='Year')),
                ('cover', models.ImageField(blank=True, default='defaults/cover.png', upload_to='covers', verbose_name='Cover')),
                ('trailer_link', models.TextField(blank=True)),
                ('categories', models.ManyToManyField(blank=True, to='movieseries.Categories', verbose_name='Categories')),
                ('link', models.ManyToManyField(blank=True, to='movieseries.Link')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('text', models.TextField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(default='icons/default.png', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieseries.Player'),
        ),
    ]
