# Generated by Django 2.1.3 on 2018-12-10 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('text', models.TextField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('icon', models.ImageField(default='icons/default.png', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movieseries.Player'),
        ),
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.ManyToManyField(blank=True, to='movieseries.Link'),
        ),
    ]
