# Generated by Django 2.1.3 on 2018-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.TextField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='Categorield',
            field=models.ManyToManyField(to='movieseries.Categories'),
        ),
    ]
