# Generated by Django 2.1.3 on 2018-11-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0002_auto_20181120_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Categorield',
        ),
        migrations.AddField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(related_name='Kategorie', to='movieseries.Categories'),
        ),
    ]
