# Generated by Django 2.1.3 on 2018-12-28 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0002_auto_20181228_2030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
