# Generated by Django 2.1.3 on 2018-11-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieseries', '0003_auto_20181120_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_link',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='added',
            field=models.DateField(auto_now_add=True, verbose_name='Dodano'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='categories',
            field=models.ManyToManyField(blank=True, to='movieseries.Categories', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.ImageField(blank=True, height_field=285, upload_to='covers', verbose_name='Okładka', width_field=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.TextField(blank=True, max_length=150, verbose_name='Reżyser'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_year',
            field=models.IntegerField(blank=True, max_length=4, verbose_name='Rok produkcji'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.TextField(max_length=200, verbose_name='Oryginalny tytuł'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title_translated',
            field=models.TextField(blank=True, max_length=200, verbose_name='Tytuł'),
        ),
    ]
